export const getImagenesCoches = (modelo_id) => {
  const rutasImagenesPorModelo = {
    1: [
      '/FOTOS/COCHES/SEATIBIZAROJO/1.jpg',
      '/FOTOS/COCHES/SEATIBIZAROJO/2.jpg',
      '/FOTOS/COCHES/SEATIBIZAROJO/3.webp',
      '/FOTOS/COCHES/SEATIBIZAROJO/4.png'
    ],
    2: [
      '/FOTOS/COCHES/HYUNDAII30NFASTBACK/1.png',
      '/FOTOS/COCHES/HYUNDAII30NFASTBACK/2.png',
      '/FOTOS/COCHES/HYUNDAII30NFASTBACK/3.png',
      '/FOTOS/COCHES/HYUNDAII30NFASTBACK/4.png'
    ],
    90: [
      '/FOTOS/COCHES/SEATLEONBLANCO/1.jpg',
      '/FOTOS/COCHES/SEATLEONBLANCO/2.jpg',
      '/FOTOS/COCHES/SEATLEONBLANCO/3.jpg',
      '/FOTOS/COCHES/SEATLEONBLANCO/4.jpg'
    ],
    91: [
      '/FOTOS/COCHES/SEATARONAAZUL/1.jpg',
      '/FOTOS/COCHES/SEATARONAAZUL/2.jpg',
      '/FOTOS/COCHES/SEATARONAAZUL/3.jpg',
      '/FOTOS/COCHES/SEATARONAAZUL/4.jpg'
    ],
    92: [
      '/FOTOS/COCHES/HYUNDAITUCSONGRIS/1.jpg',
      '/FOTOS/COCHES/HYUNDAITUCSONGRIS/2.jpg',
      '/FOTOS/COCHES/HYUNDAITUCSONGRIS/3.jpg',
      '/FOTOS/COCHES/HYUNDAITUCSONGRIS/4.jpg'
    ],
    93: [
      '/FOTOS/COCHES/HYUNDAIKONA/1.jpg',
      '/FOTOS/COCHES/HYUNDAIKONA/2.jpg',
      '/FOTOS/COCHES/HYUNDAIKONA/3.jpg',
      '/FOTOS/COCHES/HYUNDAIKONA/4.jpg'
    ],
    94: [
      '/FOTOS/COCHES/AUDIA3NEGRO/1.jpg',
      '/FOTOS/COCHES/AUDIA3NEGRO/2.jpg',
      '/FOTOS/COCHES/AUDIA3NEGRO/3.jpg',
      '/FOTOS/COCHES/AUDIA3NEGRO/4.jpg'
    ],
    95: [
      '/FOTOS/COCHES/AUDIA4AZUL/1.jpg',
      '/FOTOS/COCHES/AUDIA4AZUL/2.jpg',
      '/FOTOS/COCHES/AUDIA4AZUL/3.jpg',
      '/FOTOS/COCHES/AUDIA4AZUL/4.jpg'
    ],
    96: [
      '/FOTOS/COCHES/AUDIQ5BLANCO/1.jpg',
      '/FOTOS/COCHES/AUDIQ5BLANCO/2.jpg',
      '/FOTOS/COCHES/AUDIQ5BLANCO/3.jpg',
      '/FOTOS/COCHES/AUDIQ5BLANCO/4.jpg'
    ],
    97: [
      '/FOTOS/COCHES/VOLKSWAGENGOLFGRIS/1.jpg',
      '/FOTOS/COCHES/VOLKSWAGENGOLFGRIS/2.jpg',
      '/FOTOS/COCHES/VOLKSWAGENGOLFGRIS/3.jpg',
      '/FOTOS/COCHES/VOLKSWAGENGOLFGRIS/4.jpg'
    ],
    98: [
      '/FOTOS/COCHES/VOLKSWAGENPOLOROJO/1.jpg',
      '/FOTOS/COCHES/VOLKSWAGENPOLOROJO/2.jpg',
      '/FOTOS/COCHES/VOLKSWAGENPOLOROJO/3.jpg',
      '/FOTOS/COCHES/VOLKSWAGENPOLOROJO/4.jpg'
    ],
    99: [
      '/FOTOS/COCHES/VOLKSWAGENTROCNEGRO/1.jpg',
      '/FOTOS/COCHES/VOLKSWAGENTROCNEGRO/2.jpg',
      '/FOTOS/COCHES/VOLKSWAGENTROCNEGRO/3.jpg',
      '/FOTOS/COCHES/VOLKSWAGENTROCNEGRO/4.jpg'
    ],
    100: [
      '/FOTOS/COCHES/PEUGEOT208AZUL/1.jpg',
      '/FOTOS/COCHES/PEUGEOT208AZUL/2.jpg',
      '/FOTOS/COCHES/PEUGEOT208AZUL/3.jpg',
      '/FOTOS/COCHES/PEUGEOT208AZUL/4.jpg'
    ],
    101: [
      '/FOTOS/COCHES/PEUGEOT3008BLANCO/1.jpg',
      '/FOTOS/COCHES/PEUGEOT3008BLANCO/2.jpg',
      '/FOTOS/COCHES/PEUGEOT3008BLANCO/3.jpg',
      '/FOTOS/COCHES/PEUGEOT3008BLANCO/4.jpg'
    ],
    102: [
      '/FOTOS/COCHES/PEUGEOT508GRIS2023/1.jpg',
      '/FOTOS/COCHES/PEUGEOT508GRIS2023/2.jpg',
      '/FOTOS/COCHES/PEUGEOT508GRIS2023/3.jpg',
      '/FOTOS/COCHES/PEUGEOT508GRIS2023/4.jpg'
    ],
    103: [
      '/FOTOS/COCHES/MERCEDESCLASEANEGRO/1.jpg',
      '/FOTOS/COCHES/MERCEDESCLASEANEGRO/2.jpg',
      '/FOTOS/COCHES/MERCEDESCLASEANEGRO/3.jpg',
      '/FOTOS/COCHES/MERCEDESCLASEANEGRO/4.jpg'
    ],
    104: [
      '/FOTOS/COCHES/MERCEDESCLASECROJO/1.jpg',
      '/FOTOS/COCHES/MERCEDESCLASECROJO/2.jpg',
      '/FOTOS/COCHES/MERCEDESCLASECROJO/3.jpg',
      '/FOTOS/COCHES/MERCEDESCLASECROJO/4.jpg'
    ],
    105: [
      '/FOTOS/COCHES/MERCEDES GLCAZUL/1.jpg',
      '/FOTOS/COCHES/MERCEDES GLCAZUL/2.jpg',
      '/FOTOS/COCHES/MERCEDES GLCAZUL/3.jpg',
      '/FOTOS/COCHES/MERCEDES GLCAZUL/4.jpg'
    ]
  };
  
  return rutasImagenesPorModelo[modelo_id] || ['/FOTOS/COCHES/default.jpg'];
}; 