// Mock de catálogo de coches basado en la BBDD real
// Cada objeto representa un coche completo, listo para filtrar y mostrar

export const mockCoches = [
  {
    id: 1,
    producto_id: 1,
    modelo_id: 1,
    anio: 2022,
    kilometraje: 15000,
    color: 'Rojo',
    tipo_combustible: 'Gasolina',
    transmision: 'Manual',
    nombre_producto: 'Seat Ibiza 2022',
    descripcion: 'Seat Ibiza FR 2022, motor 1.0 TSI, 110CV, excelente estado.',
    precio: 18500,
    en_oferta: true,
    precio_oferta: 16650,
    porcentaje_descuento: 10,
    marca: 'Seat',
    modelo: 'Ibiza',
    imagen: '/FOTOS/COCHES/SEATIBIZAROJO/1.jpg',
  },
  {
    id: 2,
    producto_id: 2,
    modelo_id: 2,
    anio: 2023,
    kilometraje: 5000,
    color: 'Azul',
    tipo_combustible: 'Gasolina',
    transmision: 'Manual',
    nombre_producto: 'Hyundai i30 N Fastback',
    descripcion: 'Hyundai i30 N Fastback Performance, 280CV, increíble rendimiento.',
    precio: 39000,
    en_oferta: true,
    precio_oferta: 33150,
    porcentaje_descuento: 15,
    marca: 'Hyundai',
    modelo: 'i30 N Fastback',
    imagen: '/FOTOS/COCHES/HYUNDAII30NFASTBACK/1.png',
  },
  {
    id: 19,
    producto_id: 3,
    modelo_id: 90,
    anio: 2023,
    kilometraje: 0,
    color: 'Blanco',
    tipo_combustible: 'Gasolina',
    transmision: 'Manual',
    nombre_producto: 'Seat Leon FR',
    descripcion: 'Seat Leon FR 2023, motor 1.5 TSI, 150CV, equipamiento completo',
    precio: 28501,
    en_oferta: true,
    precio_oferta: 24225,
    porcentaje_descuento: 15,
    marca: 'Seat',
    modelo: 'Leon',
    imagen: '/FOTOS/COCHES/SEATLEONBLANCO/1.jpg',
  },
  {
    id: 20,
    producto_id: 4,
    modelo_id: 91,
    anio: 2023,
    kilometraje: 0,
    color: 'Azul',
    tipo_combustible: 'Gasolina',
    transmision: 'Automático',
    nombre_producto: 'Seat Arona',
    descripcion: 'Seat Arona 2023, motor 1.0 TSI, 110CV, SUV compacto urbano',
    precio: 21900,
    en_oferta: false,
    marca: 'Seat',
    modelo: 'Arona',
    imagen: '/FOTOS/COCHES/SEATARONAAZUL/1.png',
  },
  {
    id: 21,
    producto_id: 5,
    modelo_id: 92,
    anio: 2023,
    kilometraje: 0,
    color: 'Gris',
    tipo_combustible: 'Diésel',
    transmision: 'Manual',
    nombre_producto: 'Hyundai Tucson',
    descripcion: 'Hyundai Tucson 2023, motor 1.6 T-GDI, 150CV, SUV moderno',
    precio: 32000,
    en_oferta: false,
    marca: 'Hyundai',
    modelo: 'Tucson',
    imagen: '/FOTOS/COCHES/HYUNDAITUCSONGRIS/1.png',
  },
  {
    id: 22,
    producto_id: 6,
    modelo_id: 93,
    anio: 2023,
    kilometraje: 0,
    color: 'Rojo',
    tipo_combustible: 'Diésel',
    transmision: 'Automático',
    nombre_producto: 'Hyundai Kona',
    descripcion: 'Hyundai Kona 2023, motor 1.0 T-GDI, 120CV, SUV compacto',
    precio: 24500,
    en_oferta: false,
    marca: 'Hyundai',
    modelo: 'Kona',
    imagen: '/FOTOS/COCHES/HYUNDAIKONA/1.jpg',
  },
  {
    id: 23,
    producto_id: 7,
    modelo_id: 94,
    anio: 2023,
    kilometraje: 0,
    color: 'Negro',
    tipo_combustible: 'Diésel',
    transmision: 'Automático',
    nombre_producto: 'Audi A3 Sportback',
    descripcion: 'Audi A3 Sportback 2023, motor 2.0 TDI, 150CV, compacto premium',
    precio: 35000,
    en_oferta: false,
    marca: 'Audi',
    modelo: 'A3',
    imagen: '/FOTOS/COCHES/AUDIA3NEGRO/1.png',
  },
  {
    id: 24,
    producto_id: 8,
    modelo_id: 95,
    anio: 2023,
    kilometraje: 0,
    color: 'Azul',
    tipo_combustible: 'Diésel',
    transmision: 'Manual',
    nombre_producto: 'Audi A4',
    descripcion: 'Audi A4 2023, motor 2.0 TDI, 150CV, berlina premium',
    precio: 42000,
    en_oferta: false,
    marca: 'Audi',
    modelo: 'A4',
    imagen: '/FOTOS/COCHES/AUDIA4AZUL/1.png',
  },
  {
    id: 25,
    producto_id: 9,
    modelo_id: 96,
    anio: 2023,
    kilometraje: 0,
    color: 'Blanco',
    tipo_combustible: 'Diésel',
    transmision: 'Manual',
    nombre_producto: 'Audi Q5',
    descripcion: 'Audi Q5 2023, motor 2.0 TDI, 204CV, SUV premium',
    precio: 52000,
    en_oferta: false,
    marca: 'Audi',
    modelo: 'Q5',
    imagen: '/FOTOS/COCHES/AUDIQ5BLANCO/1.png',
  },
  {
    id: 26,
    producto_id: 10,
    modelo_id: 97,
    anio: 2023,
    kilometraje: 0,
    color: 'Gris',
    tipo_combustible: 'Gasolina',
    transmision: 'Automático',
    nombre_producto: 'Volkswagen Golf',
    descripcion: 'Volkswagen Golf 2023, motor 1.5 TSI, 150CV, compacto alemán',
    precio: 28000,
    en_oferta: true,
    precio_oferta: 23800,
    porcentaje_descuento: 15,
    marca: 'Volkswagen',
    modelo: 'Golf',
    imagen: '/FOTOS/COCHES/VOLKSWAGENGOLFGRIS/1.png',
  },
  {
    id: 27,
    producto_id: 11,
    modelo_id: 98,
    anio: 2023,
    kilometraje: 0,
    color: 'Rojo',
    tipo_combustible: 'Gasolina',
    transmision: 'Manual',
    nombre_producto: 'Volkswagen Polo',
    descripcion: 'Volkswagen Polo 2023, motor 1.0 TSI, 110CV, urbano eficiente',
    precio: 22000,
    en_oferta: false,
    marca: 'Volkswagen',
    modelo: 'Polo',
    imagen: '/FOTOS/COCHES/VOLKSWAGENPOLOROJO/1.png',
  },
  {
    id: 28,
    producto_id: 12,
    modelo_id: 99,
    anio: 2023,
    kilometraje: 0,
    color: 'Negro',
    tipo_combustible: 'Gasolina',
    transmision: 'Automático',
    nombre_producto: 'Volkswagen T-Roc',
    descripcion: 'Volkswagen T-Roc 2023, motor 1.5 TSI, 150CV, SUV compacto',
    precio: 31000,
    en_oferta: false,
    marca: 'Volkswagen',
    modelo: 'T-Roc',
    imagen: '/FOTOS/COCHES/VOLKSWAGENTROCNEGRO/1.png',
  },
  {
    id: 29,
    producto_id: 13,
    modelo_id: 100,
    anio: 2023,
    kilometraje: 0,
    color: 'Azul',
    tipo_combustible: 'Gasolina',
    transmision: 'Automático',
    nombre_producto: 'Peugeot 208',
    descripcion: 'Peugeot 208 2023, motor 1.2 PureTech, 130CV, diseño francés',
    precio: 24000,
    en_oferta: false,
    marca: 'Peugeot',
    modelo: '208',
    imagen: '/FOTOS/COCHES/PEUGEOT208AZUL/1.png',
  },
  {
    id: 30,
    producto_id: 14,
    modelo_id: 101,
    anio: 2023,
    kilometraje: 0,
    color: 'Blanco',
    tipo_combustible: 'Gasolina',
    transmision: 'Automático',
    nombre_producto: 'Peugeot 3008',
    descripcion: 'Peugeot 3008 2023, motor 1.6, 180CV, SUV francés premium',
    precio: 35000,
    en_oferta: true,
    precio_oferta: 29750,
    porcentaje_descuento: 15,
    marca: 'Peugeot',
    modelo: '3008',
    imagen: '/FOTOS/COCHES/PEUGEOT3008BLANCO/1.png',
  },
  {
    id: 31,
    producto_id: 15,
    modelo_id: 102,
    anio: 2023,
    kilometraje: 0,
    color: 'Gris',
    tipo_combustible: 'Diésel',
    transmision: 'Automático',
    nombre_producto: 'Peugeot 508',
    descripcion: 'Peugeot 508 2023, motor 1.6 PureTech, 180CV, berlina francesa',
    precio: 37500,
    en_oferta: false,
    marca: 'Peugeot',
    modelo: '508',
    imagen: '/FOTOS/COCHES/PEUGEOT508GRIS2023/1.png',
  },
  {
    id: 32,
    producto_id: 16,
    modelo_id: 103,
    anio: 2023,
    kilometraje: 0,
    color: 'Negro',
    tipo_combustible: 'Gasolina',
    transmision: 'Automático',
    nombre_producto: 'Mercedes Clase A',
    descripcion: 'Mercedes Clase A 2023, motor 2.0, 163CV, compacto premium',
    precio: 39000,
    en_oferta: false,
    marca: 'Mercedes',
    modelo: 'Clase A',
    imagen: '/FOTOS/COCHES/MERCEDESCLASEANEGRO/1.png',
  },
  {
    id: 33,
    producto_id: 17,
    modelo_id: 104,
    anio: 2023,
    kilometraje: 0,
    color: 'Rojo',
    tipo_combustible: 'Gasolina',
    transmision: 'Manual',
    nombre_producto: 'Mercedes Clase C',
    descripcion: 'Mercedes Clase C 2023, motor 2.0, 204CV, berlina premium',
    precio: 45000,
    en_oferta: true,
    precio_oferta: 36000,
    porcentaje_descuento: 20,
    marca: 'Mercedes',
    modelo: 'Clase C',
    imagen: '/FOTOS/COCHES/MERCEDESCLASECROJO/1.jpeg',
  },
  {
    id: 34,
    producto_id: 18,
    modelo_id: 105,
    anio: 2023,
    kilometraje: 0,
    color: 'Azul',
    tipo_combustible: 'Gasolina',
    transmision: 'Automático',
    nombre_producto: 'Mercedes GLC',
    descripcion: 'Mercedes GLC 2023, motor 2.0, 194CV, SUV premium alemán',
    precio: 55000,
    en_oferta: false,
    marca: 'Mercedes',
    modelo: 'GLC',
    imagen: '/FOTOS/COCHES/MERCEDES GLCAZUL/1.png',
  },
];

// Imagen para el banner (elige una real del catálogo)
export const bannerCoche = "/FOTOS/fot11.png";
